# -*- coding: utf-8 -*-
"""ybi_sol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mOz-VDB6pphUjsD6128yWXHssBkt65UH
"""

import pandas as pd
import numpy as np
df= pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Financial%20Market%20News.csv', encoding= "ISO-8859-1")
df.head()
' '.join(str(x) for x in df.iloc[1,2:27])
news = []
for rows in range(0, len(df.index)):
  news.append(' '.join(str(x) for x in df.iloc[1,2:27]))
X= news
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(lowercase = True , ngram_range=(1,1))
X = cv.fit_transform(X)
y= df['Label']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y , random_state=2529, test_size=0.3, stratify= y)
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=200)
rf.fit(X_train, y_train)
y_pred= rf.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))